name: Push Build to Artifactory


on: workflow_dispatch 


jobs:
 build:
   runs-on: ubuntu-latest
  
   steps:
   # This action checks out the code from the repository
   - name: Checkout Code
     uses: actions/checkout@v2


   # This action sets up the JFrog CLI with the Artifactory URL and access token     
   - uses: jfrog/setup-jfrog-cli@v3
     env:
       JF_URL: "https://devops4.jfrog.io"
       JF_ACCESS_TOKEN: "eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiIyeWlvY1Jta1hZbXZsQS1yVUF4V2U5NGN5U1RfcTMyU0hwSnBFVmFqYmo0In0.eyJzdWIiOiJqZmFjQDAxaHFrbXNmaHBqamN5MDZjYTBjZmowMWRyL3VzZXJzL2FkbWluIiwic2NwIjoiYXBwbGllZC1wZXJtaXNzaW9ucy9hZG1pbiIsImF1ZCI6IipAKiIsImlzcyI6ImpmZmVAMDFocWttc2ZocGpqY3kwNmNhMGNmajAxZHIiLCJleHAiOjE3MTE2MjM5ODcsImlhdCI6MTcwOTAzMTk4NywianRpIjoiMzNiZjg0ZjktMGFlYi00YTZmLWE1OTQtZWJhYjE2MzEzOGRlIn0.GmtmD56oj7pQoWk4PAQhuC4zE3AMAAP83RKnHYe81NQFwlP61shREqb-Gx6d_b1HORkVo21Gen1xzWHesFpWc0E6Yen85MltQLccmqhEMZSQ_Yl2y1TanMx2_RiEiMnyMqyF6hmkJVUCGD6DmxnD-e5dNWc9Od4S6Y-D2LK2EdZP2C-QwhEqG_s0gZgphBUG8O803ENLpTAdSsPLC3e8cETDUviEhMIkrP_xoG4y2hl4SlBiPcZr1jBCKLonoz53cAtc8cnhnZ-Qzh_xvqYc55L204o6isz3muvU4m8lk9Yhg8pUt-aFJKmMtpaZ9vchAh0L2NXKvRtOo9oqKLFveA"


   # This command adds a new server configuration to the JFrog CLI   
   - run: |
       export SERVER_ID="devops4"
       jf c add $SERVER_ID --url="https://devops4.jfrog.io" --access-token="eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiIyeWlvY1Jta1hZbXZsQS1yVUF4V2U5NGN5U1RfcTMyU0hwSnBFVmFqYmo0In0.eyJzdWIiOiJqZmFjQDAxaHFrbXNmaHBqamN5MDZjYTBjZmowMWRyL3VzZXJzL2FkbWluIiwic2NwIjoiYXBwbGllZC1wZXJtaXNzaW9ucy9hZG1pbiIsImF1ZCI6IipAKiIsImlzcyI6ImpmZmVAMDFocWttc2ZocGpqY3kwNmNhMGNmajAxZHIiLCJleHAiOjE3MTE2MjM5ODcsImlhdCI6MTcwOTAzMTk4NywianRpIjoiMzNiZjg0ZjktMGFlYi00YTZmLWE1OTQtZWJhYjE2MzEzOGRlIn0.GmtmD56oj7pQoWk4PAQhuC4zE3AMAAP83RKnHYe81NQFwlP61shREqb-Gx6d_b1HORkVo21Gen1xzWHesFpWc0E6Yen85MltQLccmqhEMZSQ_Yl2y1TanMx2_RiEiMnyMqyF6hmkJVUCGD6DmxnD-e5dNWc9Od4S6Y-D2LK2EdZP2C-QwhEqG_s0gZgphBUG8O803ENLpTAdSsPLC3e8cETDUviEhMIkrP_xoG4y2hl4SlBiPcZr1jBCKLonoz53cAtc8cnhnZ-Qzh_xvqYc55L204o6isz3muvU4m8lk9Yhg8pUt-aFJKmMtpaZ9vchAh0L2NXKvRtOo9oqKLFveA" --interactive=false


   # This action creates a new test file and uploads it to Artifactory   
   - name: Push Build to Artifactory
     run: |
       echo "test file " > test.txt
       export BUILD_NAME="my-build"
       export BUILD_MODULE="my-module"
       export BUILD_NUMBER="1"


       export PATH_TO_DIRECTORY="tf-trial/workspaces/jfrog-ws1/"
      
       jf rt upload "test.txt" $PATH_TO_DIRECTORY --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE


   # This action publishes the build information to Artifactory and deletes older builds
   - name: Build to Artifactory
     run: |
       jf rt build-publish $BUILD_NAME $BUILD_NUMBER
     
       jf rt bdi c --max-builds=1
