name: Push Build to Artifactory


on: workflow_dispatch 


jobs:
 build:
   runs-on: ubuntu-latest
  
   steps:
   # This action checks out the code from the repository
   - name: Checkout Code
     uses: actions/checkout@v2


   # This action sets up the JFrog CLI with the Artifactory URL and access token     
   - uses: jfrog/setup-jfrog-cli@v3
     env:
       JF_URL: "https://venkata12.jfrog.io"
       JF_ACCESS_TOKEN: "cmVmdGtuOjAxOjE3MzkzMzE1NzY6VkdtNzdnZENhSGdaWG1iZXQ5aUtpTFUwQk8z"


   # This command adds a new server configuration to the JFrog CLI   
   - run: |
       export SERVER_ID="venkata12"
       jf c add $SERVER_ID --url="https://venkata12.jfrog.io" --access-token="cmVmdGtuOjAxOjE3MzkzMzE1NzY6VkdtNzdnZENhSGdaWG1iZXQ5aUtpTFUwQk8z" --interactive=false


   # This action creates a new test file and uploads it to Artifactory   
   - name: Push Build to Artifactory
     run: |
       echo "test file " > test.txt
       export BUILD_NAME="my-build"
       export BUILD_MODULE="my-module"
       export BUILD_NUMBER="1"


       export PATH_TO_DIRECTORY="tf-trial/workspaces/jfrog-ws1/"
      
       jf rt upload "test.txt" $PATH_TO_DIRECTORY --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE


   # This action publishes the build information to Artifactory and deletes older builds
   - name: Build to Artifactory
     run: |
       jf rt build-publish $BUILD_NAME $BUILD_NUMBER
     
       jf rt bdi c --max-builds=1
